version: "3.9"  # optional since v1.27.0
services:
    api:
        # image: amradel/nestjs-dockerized
        build: 
              dockerfile: Dockerfile
              context: .
        depends_on:
              - mysql
        enviroment:
              DATABASE_URL: 'http://127.0.0.1:3306'
              NODE_ENV: devlopment
              PORT: 3000
        ports:
            - "8000:3000"
    mysql:
      image: mysql:8.0.28
      ports: 
          - "3306:3306"
      enviroment:
          MYSQL_USER: root
          MYSQL_PASSWORD: password 
          MYSQL_DB: taskManager_db
        



