
version: "3"
services:
  server:
    container_name: task-manager-nest
    image: task-manager-docker-registry/server-image
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 3000:3000
  # separate service for run migrations while deploy
  migration:
    image: my-docker-registry/server-image
    env_file:
      - .env
    command: './wait-for-it.sh myappname-postgres:5432 -- npm run migrations:up:prod'
    depends_on:
      - postgres
  postgres:
    # container name using like a host in other services
    container_name: myappname-postgres
    image: postgres:11
    restart: always
    # volume with database data
    volumes:
      - ./volumes/postgres-prod:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432